# Generated by Django 4.2.6 on 2023-11-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctors_alter_user_mobile_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
