# Generated by Django 4.2.6 on 2023-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_app',
            field=models.BooleanField(default=False),
        ),
    ]
