# Generated by Django 4.2.6 on 2023-11-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
