# Generated by Django 4.2.6 on 2023-11-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_patient_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
