# Generated by Django 4.2.6 on 2023-11-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_patient_profile_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_profile',
            name='user',
        ),
    ]
